bblfsh/sdk

assets/skeleton/bindata.go
etc/skeleton/git/hooks/pre-commit

fixes problem described by [It's possible to commit something, ignoring changes in managed files #15
](https://github.com/bblfsh/sdk/issues/15)

Fix pre-commit hook. Close issue #15

---

protocol/driver.go
protocol/server.go
protocol/server_test.go
protocol/uastclient.go

* created UASTClient to encapsulate ParseUAST request to the
NativeClient and separate it from Server logic.

refactor Server/Driver

---

protocol/driver.go
protocol/driver_test.go

This command outputs a tab-separated list of tokens.

driver: add tokenize subcommand

---

uast/uast.go

* Java `>>>`: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/op3.html
* C# `>>>`: https://msdn.microsoft.com/en-us/library/x0ax6803(v=vs.100).aspx

uast: add unsigned right shift operator

---

uast/tonoder.go
uast/tonoder_test.go

Merge https://github.com/bblfsh/sdk/pull/85 first, this is, ignore the first commit in this patch when reviewing this PR.
Some parsers, like the one we are using in the bash-driver, place the root of the AST at the top level of their JSON output, while others, like the one we use in the java-driver, place the root deeper into the JSON due to some scaffolding they use (so it has to be unwrapped before use).
Prior to this patch, the SDK assumes the java-driver style and tried to unwrap every AST looking for its root node.  This patch adds the `BaseToNoder.TopLevelIsRootNode` option, with the same default behaviour than the old behaviour, that will allow processing bash-like ASTs when set.
As a bonus, I have added some tests for the error checking of `BaseToNoder.ToNode` that were missing.

Add support for parsers that place the root node at the top level of the AST

---

assets/skeleton/bindata.go
etc/skeleton/README.md.tpl

Small style fix + UAST converter dependencies requirement

Update of README template of the drivers

---

assets/build/bindata.go
etc/build/etc/it.bash
protocol/driver.go

* add --format=prettyjson option, this removes the dependency
of Python from integration-tests.

driver: add prettyjson format

---

protocol/driver/driver_test.go
protocol/driver/parser.go
protocol/driver/parser_test.go
protocol/driver/positions.go
protocol/driver/positions_test.go
protocol/driver/server_test.go
protocol/native/objecttonoder.go
uast/pretty.go
uast/uast.go

* add a new TransformationASTParser which can apply an arbitrary transformation to the result of the main parser (native.Parser most of the time).
* added FillOffsetFromLineCol and FillLineColFromOffset transformations.

Fill positions

---

uast/ann/ann.go
uast/ann/ann_test.go

Fixes #94.
`ann.Error` now receives an error instead of a message and the error returned by `Apply` now includes the node that triggered the error.
I modified a test with all the possible checks you would like to perform in the returned error as an example of use.

ann: add descriptive errors to the error rule

---

protocol/native/objecttonoder.go

As suggested in: https://github.com/bblfsh/documentation/pull/24#discussion_r119645264

Improved godocs of ann.ObjectToNoder

---

uast/ann/ann.go

Fixes #132 
It can be seen at work at https://github.com/bblfsh/python-driver/pull/29 and https://github.com/bblfsh/java-driver/pull/26

annotations: Add support for multiple roles

---

assets/build/bindata.go
etc/build/make/rules.mk

build: Fix problem with GOPATH with multiple entries

---

protocol/protocol.go

Small renaming-related comment fixes

---

Makefile
README.md

https://github.com/bblfsh/sdk/issues/143

added rule to Makefile to install SDK

---

assets/build/bindata.go
etc/build/make/rules.mk

Fixed latest Dockerhub tags generation

---

assets/build/bindata.go
etc/build/make/rules.mk
sdk/driver/integration/suite_test.go
sdk/driver/server.go

Now `make integration-test` executes the tests against a docker container just built.

sdk: intregration-test now is self-contained

---

assets/build/bindata.go
etc/build/make/rules.mk

Remove the (removed) docgen Makefile target

---

uast/node.go
uast/node_test.go

Composed position keys

---

uast/uast.go
uast/uast_test.go

Restore Tokens as a public func since its also used by drivers' tests

---

uast/node.go
uast/node_test.go

New options for ObjectToNode.
This new features are required for php-driver, I made the modification with the idea, to be as much generic as possible.

uast: ObjectToNode, IsNode, Modifier and OnToNode fields

---

protocol/types.go

IDK what the fuck happened there...

Remove some duplicated calls

---

uast/node.go
uast/node_test.go

Small improvement as discussed in https://github.com/bblfsh/sdk/issues/214

Json values in props

---

assets/build/bindata.go
etc/build/etc/build/Dockerfile.build.alpine.tpl

Should fix build issues in https://github.com/bblfsh/python-driver/pull/144 and https://github.com/bblfsh/java-driver/pull/64.

do not rely on workdir while running wget in Docker build

---

sdk/driver/encoding.go
sdk/driver/encoding_test.go

add method for Encoding type to encode/decode messages

---

assets/skeleton/bindata.go
etc/skeleton/Makefile
etc/skeleton/native/README.md.tpl

Improve driver bootstraping and error messages

---

protocol/types.go
sdk/driver/driver.go
sdk/driver/driver_test.go

Fixes #226 (language was already added in a previous change).

Add filename to ParseResponse

---

manifest/manifest.go

Alpine 3.7

---

.travis.yml
assets/build/bindata.go
assets/skeleton/bindata.go
etc/build/etc/build/Dockerfile.build.alpine.tpl
etc/skeleton/.travis.yml
etc/skeleton/manifest.toml.tpl
manifest/manifest_test.go

Move to Go 1.9

---

assets/build/bindata.go
etc/build/etc/build/Dockerfile.build.alpine.tpl

Update no-pic-patch to the required one for Alpine 3.7 and Go 1.9

---

cli/bblfsh-sdk-tools/cmd/fixtures.go

Optional proto message fixture.
We need UAST fixture because we also use gRPC with `uast.Node` type.
Although for our purposes we don't really care about content because it's processed by sourced-ml.
It should be just valid.

Tools fixtures: create proto message fixture

---

uast/transformer/ast.go
uast/transformer/legacy.go

Restore Line/Col

---

uast/transformer/ast.go
uast/transformer/conv.go
uast/transformer/ops_test.go
uast/transformer/transformer.go
uast/transformer/transformer_test.go

* Fix issue with combining typed maps with generic ones.
* Increase test coverage.

Fix issue with generic mappings

---

protocol/types.go

Added info about protocol.Status

---

sdk/driver/fixtures/docker.go

fixtures: check if docker is installed before running tests

---

assets/build/bindata.go
etc/build/make/rules.mk
sdk/driver/fixtures/docker.go

fixtures: use docker api instead of cmd; fix make test

---

sdk/driver/exec.go
sdk/driver/exec_test.go
sdk/driver/fixtures/fixtures.go

Expose native driver errors properly

---

sdk/driver/fixtures/fixtures.go

fixtures: handle response errors correctly

---

assets/build/bindata.go
build/build.go
build/build_test.go
etc/build/Dockerfile.tpl

Allow to run apt/apk in a final build

---

build/push.go

Allow docker push on `vX` branches, but don't push `latest` in this case.

Allow docker push on vX branches, but don't push latest

---

uast/nodes/nodesproto/nodesproto.go
uast/nodes/nodesproto/nodesproto_test.go

Currently, SDK hides the fact that binary format for UAST assigns IDs to nodes. But, as was mentioned in the design doc and a recent [issue](https://github.com/bblfsh/web/pull/152), `uast-viewer` needs node IDs in the response.
This CL adds a new method to `nodeproto` package that allows to read a flat list of nodes and skip the tree reconstruction. This method will be used in the Dashboard server to send UASTs to the frontend.

Allow to read raw UAST graph

---

uast/role/role.go
uast/role/role_test.go

Currently, there is no way to check if a particular role ID is valid or not. This CL adds a function that does this check.

role: allow to check if a role is valid

---

uast/nodes/external.go
uast/nodes/node.go
uast/nodes/node_test.go

Allow checking if two nodes are the same and implement the function to get a map key for a node.

Allow to check if two nodes are the same

---

Gopkg.lock

Update XPath dependency

---

driver/driver.go

driver: move ParseMode function from the client to SDK

---

driver/fixtures/fixtures.go

fixtures: correctly trim namespace for the node blacklist

---

build/test.go

Allow to skip syntax error tests

---

README.md

https://bblfsh.gitbooks.io/documentation/writing-a-driver/babelfish-sdk.html#creating-the-drivers-initial-structure

Update driver creation docs to match docs site

---

uast/iter.go
uast/types.go
uast/uast.go

Improve documentation for a `uast` package. Covers the UAST schema and related functions.

Improve documentation (part 1)

---

assets/skeleton/bindata.go
etc/skeleton/.travis.yml
etc/skeleton/Gopkg.toml
etc/skeleton/build.yml.tpl
etc/skeleton/manifest.toml.tpl

* Update SDK version for new drivers.
* Update Go version for new drivers and CI
* Update bblfshd version for CI

Update versions of SDK and bblfshd in the driver skeleton

---

protocol/driver.pb.go
uast/role/role.go

Fixes bblfsh/documentation/issues/233.

Improve some role descriptions, update bindata.

---

build/sdk_update.go

Fix template function name broken by auto refactoring

---

protocol/driver.go

Currently, clients call `DialOptions` to get the default dial options that should work well for a Babelfish gRPC client. But this config does not include the default size setting that is set for the server.
This change sets the default message size in both the client and the server options.
Related to https://github.com/bblfsh/sdk/issues/384

Set a default max message size for all gRPC clients and servers

---

uast/nodes/external.go
uast/role/role.go
uast/transformer/ops.go

* Typos
* Methods improvements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/413)

Minor improvements

---

Jenkinsfile
cmd/bblfsh-drivers-updater/update.go
cmd/bblfsh-drivers-updater/utils/utils.go

The logic is triggered on curl and runs updater utility https://github.com/bblfsh/sdk/pull/418
**Usage**
- connect to the cluster
- execute curl
```shell
curl -X POST -H "Content-Type: application/json" \
-vs https://jenkins.k8s.pipeline.prod.srcd.run/generic-webhook-trigger/invoke\?token\=update \
-d @- <<'EOF'
{
"ref": "refs/heads/master",
"sdk_version": "3.2.2",
"script": "echo c > c.txt",
"branch": "create-a-file-c",
"commit_msg": "create-a-file commit msg"
}
EOF
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/420)

add Jenkinsfile to trigger auto-update all drivers repositories

---

Jenkinsfile
cmd/bblfsh-drivers-updater/update.go
cmd/bblfsh-drivers-updater/utils/utils.go

A few minor fixes to driver/SDK updater:
- Allow customizing PR title and text.
- Do not add new files to Git automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/437)

Driver updater fixes

---

cmd/bblfsh-sdk/cmd/request.go
cmd/bblfsh-sdk/main.go

Signed-off-by: kuba-- <kuba@sourced.tech>
Originally this tool was part of PR to `cpp-driver`. As @dennwc suggested, I'm moving it to `bblfsh-sdk`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/436)

Add parse request tool

---

Jenkinsfile
assets/skeleton/bindata.go
etc/skeleton/Jenkinsfile.tpl

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/442)

add jenkins slack notifications

---

protocol/driver.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/445)

add DriverFromClient constructor
