bblfsh/sdk

etc/build/make/help.mk
For the native runtime... it should be needed `*-native-internal` rules, shouldn't it?
=> Internal rules hint

uast/tonoder.go
Python AST uses line and column, the later was missing from BaseToNoder but was present in the StartPosition struct member of the Node.
=> Added ColumnKey to BaseToNoder and load its value into (existing) Node.StartPosition.Col

assets/build/bindata.go, etc/build/etc/it.bash, protocol/cmd/drivermain.go
This PR changes format of reference results for UAST in integration tests from JSON to UAST pretty printing (Go-style AST). This is easy for manual verification and produces nicer diffs.
=> driver: use pretty printed UAST for integration tests

uast/pretty.go
Closing brace for node had an extra indent.
=> uast: fix indentation on pretty printed UAST

uast/uast.go
Basic ones. I didn't add some more exotic ones like pow (** in Python, ^ in other languages) or the two or more kinds of division but we could discuss if we need to add them or add an "BinaryAritmeticOther" with an annotation.
=> uast: added arithmetic operators

uast/tonoder.go, uast/tonoder_test.go, uast/uast.go
This PR adds two settings to allow the translation to promote properties (dictionary keys) with a list value to its own node (aka "property-lists"). Without this PR the nodes in the list will be added as children of the enclosing dictionary with the only reference to the key being the internalRole property so if we have:
```text
{If: { body: [expr, expr, expr],
test: [exprtest, exprtest],  
else: [elseexpr, elseexpr]}
}
```
In the UAST we would get:
```text
{If: {Children: [expr, expr, expr, exprtest, exprtest, elseexpr, elseexpr]}}
```
This can work in some cases since the nodes can have multiple roles so a human/machine reading the UAST could still see the type of every nodes, so in this case expr would have the roles Expression and IfBody and the args would have Argument and Arguments, …
=> sdk tonoder: listproperty to parent node

uast/uast.go
This complements the MapLiteral UAST role adding MapKey and MapValue.
=> uast: added MapKey and MapValue roles

uast/uast.go
Second try fixing the mess of my previous PR history, reseting my fork master to this one.
Original text:
Adds:
BinaryExpression
BinaryExpressionLeft
BinaryExpressionRight
BinaryExpressionOperator
Usually BinaryExpression would be a parent node while BinaryExpression[Left|Right|Operator] would be additional roles added to the left side, right side and existing operator roles.
=> uast: added roles for BinaryExpressions 

uast/tonoder.go, uast/tonoder_test.go
This fix a bugfix that I introduced some commits ago which caused the SyntheticTokens not being translated. It also adds a unittest to detect this problem in the future.
=> Fix for SyntheticTokens not being translated, unittest added

assets/build/bindata.go, etc/build/make/bootstrap.mk
According to [documentation](https://doc.bblf.sh/user/getting-started.html#run), only the first 6 chars from the commit hash are used in the image tag, but 7 are used actually. Since 6 seems better than 7, I've changed the implementation instead of docs.
=> Use 6 chars from commit hash

protocol/driver/server.go, protocol/native/objecttonoder.go, uast/ann/ann_test.go
Merge https://github.com/src-d/go-errors/pull/6 first.
Part of https://github.com/src-d/backlog/issues/700.
=> update to go-errors migration to gopkg.in

assets/skeleton/bindata.go, etc/skeleton/driver/main.go.tpl, etc/skeleton/driver/normalizer/parser.go, protocol/driver/driver.go, protocol/driver/driver_test.go, protocol/driver/parser.go, protocol/driver/parser_test.go, protocol/driver/positions_test.go, protocol/generated.pb.go, protocol/generated.proto, protocol/internal/testdriver/main.go, protocol/internal/testnative/main.go, protocol/native/native.go, protocol/protocol.go, protocol/protocol_test.go, protocol/server.proteus.go
Initially we thought we would expose the raw native AST
to the external interface. This is not the case, since
all requests going in and out of the driver use *uast.Node
type, so the only difference is if it's annotated or not.
This commit removes ParseAST from the protocol and leaves
just ParseUAST. This reduces code paths, since parsers at
different levels can all use the same interface (UASTParser).
ASTParser still exists but only in the 'native' package, as
an internal detail about communciation betwee native parser
and UAST conversor inside a driver.
=> remove ParseAST code from protocol and driver

assets/skeleton/bindata.go, etc/skeleton/driver/main.go.tpl, etc/skeleton/driver/normalizer/parser.go, protocol/driver/driver.go, protocol/driver/driver_test.go, protocol/driver/parser.go, protocol/driver/parser_test.go, protocol/driver/positions_test.go, protocol/driver/server.go, protocol/generated.pb.go, protocol/generated.proto, protocol/internal/testdriver/main.go, protocol/internal/testnative/main.go, protocol/native/native.go, protocol/protocol.go, protocol/protocol_test.go, protocol/server.proteus.go
Now driver.UASTParser conforms to protocol.Parser. That is,
it does not use a second return value for error and uses the
error handling of ParseUASTRequest.
=> driver: do not return error on ParseUAST

protocol/driver/client.go, protocol/driver/client_test.go
Added a convenience interface to communicate with bblfsh drivers directly. This will be used by bblfsh/server but might be used separately.
=> add driver.Client to communicate with drivers

uast/uast_test.go, uast/utils.go
This adds uast.utils.CyclomaticComplexity that for a given Node (and children) will calculate the cyclomatic complexity. Also adds a unittest.
This doesn't include the NPath complexity.
=> Added function for cyclomatic complexity + unittest

assets/build/bindata.go, etc/build/make/rules.mk, protocol/driver/driver.go, protocol/driver/driver_test.go, uast/ann/ann.go, uast/ann/ann_test.go, uast/ann/xpathdescription.go, uast/ann/xpathdescription_test.go
Fixes https://github.com/src-d/backlog/issues/701.
- ann: Add Rule.String to create markdown tables using XPath like notation
Every predicate is now a type, implementing the new Predicate interface
and they know how to print themselves in XPath-like notation.
The processing of the rule tree is implemented as a folding operation
by the new xPathDescription type.
- makefile: Add new docgen target
This adds the new rule `docgen` to the makefile, that generates
documentation for the driver.
It also adds docgen as a prerequisite to build.
Right now it only prints the rules as a markdown table to a ANNOTATION.md file.
=> Autogenerate conversion tables for UAST

protocol/jsonlines/decoder.go
This fix all "buffer size excedeed" problems with all the Python files I tested (all of the modules in Python 2.7 and 3.6 stdlibs, including some huge ones) but eventually a dynamic allocation alternative will be needed.
=> Increase JSON decoder buffer size to 4Mb

protocol/jsonlines/decoder.go
This fix was trivial to code,  easy to explain but was a hell to debug. 
When there was any error on the reader from the native driver, the driver stdin was not being consumed until the next newline. This caused that on the next request it would still trying to write to its stdout while the Go wrapper would try to read the new request into its stdin, hanging.
This also changes the read to be done by reading buffer-sized chunks into a slice so this should also fix the "buffer size exceeded" problem.
The driver images should be rebuild once this is merged since it's a pretty annoying bug.
=> Fix hangs when the reading from the native driver raised an error before all input was consumed

uast/ann/ann.go, uast/ann/ann_test.go, uast/uast.go
- `NewNode()` will add the Unannotated role to all new nodes by default, `AddRoles()` will remove it the first time another role is added. I also tried the other way, that is, adding `Unannotated` when a Node has no roles after `Apply()` but since it also runs over the children recursively it was more complicated (it had to check and remove the `Unannotated` node anyway).
- Tests updated. Also tested with the Python and Java driver integration tests (next PRs will update those).
- Fixes an unrelated bug from a previous commit of a possible recursive `axis.String` call that my linter catched.
=> Adds and remove the Unannotated status to nodes

protocol/native/objecttonoder.go, protocol/native/objecttonoder_test.go
New feature to promote string properties to full nodes, similar to the existing one that allows to promote the keys in properties holding arrays to nodes.
Like in the previous case the key name will be the `internalType` and the string value will be set as the node `Token`.
This allows to convert something like:
```python
import numpy as np
```
With native (simplified) AST:
```python
{
"ast_type": "alias",
"asname": "np",
"name": "numpy"
}
```
To this (simplified & prettified) UAST:
```python
{
.  .  .  .  .  Roles: ImportPath,SimpleIdentifier
.  .  .  .  .  TOKEN "numpy"
.  .  .  .  .  Children: {
.  .  .  .  .  .  0: alias.asname {
.  .  .  .  .  .  .  Roles: ImportAlias,SimpleIdentifier
.  .  .  .  .  .  .  TOKEN "np"
.  .  .  .  .  .  .  Properties: {
.  .  .  .  .  .  .  . …
```
=> New feature to promote string properties to nodes

protocol/native/objecttonoder.go
Currently new nodes are promoted and include the same property name, which are usually included in `TokenKeys` and this causes these nodes to include the token by default, which is then duplicated and used in this parent umbrella node where they shouldn't.
This change renames the property, allowing it to be handled independently.
=> objecttonoder: Use a different proper name for promoted string keys

assets/skeleton/bindata.go, etc/skeleton/driver/normalizer/parser.go, protocol/native/objecttonoder.go
Part of src-d/backlog/issues/889
=> New ToNoder option to fill missing position elements. Unified parser.go skeleton.

README.md
With upstream fix it no longer applies, thanks to https://github.com/gogo/protobuf/pull/336
=> docs: Remove explanation about manual editing of autogenerated files

sdk/driver/common.go, sdk/driver/driver.go, sdk/driver/native.go, sdk/driver/server.go, sdk/server/logger.go, sdk/server/server.go
In order to improve the logging in server and clients, I created a `LoggerFactory` and `Logger` interface to use exactly the same configuration in the drivers and server.
With the goal of miss the outputs of all the driver and server, I added too the "-log-fields", to pass information to the driver to log togetther the common line "
```
$ python driver --log-level debug --log-format text --log-fields '{"language":"python", "container":"AABBCCDD"}'
[2017-09-28T13:48:13Z]  INFO python-driver version: dev-0b6ddb4-dirty (build: 2017-09-28T13:45:46Z) container=AABBCCDD language=python
[2017-09-28T13:48:13Z] DEBUG executing native binary ... container=AABBCCDD language=python
[2017-09-28T13:48:13Z]  INFO server listening in localhost:9432 (tcp) container=AABBCCDD language=python …
```
=> server: logger configurations

sdk/server/logger.go, sdk/server/logger_test.go
Sometime is more convenient configure the default logger instead of use a custom instance. The new method `LoggerFactory.Apply` applies the factory settings to the default one.
This is really useful when third-party loggers are using logrus and the message are printed in a complete random style. (eg.: `libcontainer`)
=> sdk: server.LoggerFactory added Apply method to modify the standard logrus logger

protocol/types.go
Currently at the bblfshd, all the requests has a timeout for waiting for a driver, instead of being something hardcoded or configured in the server, I believe is better having this as a per request configuration.
The comment doesn't explain this, because is a detail of implementation and in the future may change, but a timeout maybe will be still required.
=> protocol: *Request include timeout for waiting for a driver at bblfshd

uast/node.go
Signed-off-by: Alfredo Beaumont <alfredo.beaumont@gmail.com>
This should consider a node without a position as equal to any other, with or without a position, and thus make stable sort actually stable.
=> uast: Make node ordering actually stable when there're no positions.

uast/fixtures/java_example_1.json, uast/node.go, uast/node_test.go
=> ToNoder.SpecificTokenKeys to specificy fields to use as Token for some nodes

uast/ann/ann.go, uast/ann/ann_test.go
Fixes bblfsh/python-driver/issues/130
=> Do the duplicate removal on all node roles, not only the new ones.

sdk/driver/driver.go, sdk/driver/driver_test.go
(e. g. when running a driver directly).
=> driver: fill the language when the Request.Language

uast/node.go, uast/node_test.go
Example of real AST (typescript):
```
{
"col": 1,
"declarationList": {
"col": 1,
"declarations": [...],
"end": 19,
"flags": ["Const", "BlockScoped"],
"kind": "VariableDeclarationList",
"line": 1,
"pos": 0
},
"end": 20,
"flags": [],
"kind": "VariableStatement",
"line": 1,
"modifierFlagsCache": 536870912,
"pos": 0
}
```
Now driver always return:
```
expected object of type map[string]interface{}, got: "Const"
Writing fixtures/simple.ts.uast ...
```
Please, guide me how to fix it if current solution is wrong.
Thanks!
=> Fix parsing ast with array

uast/node.go, uast/node_test.go
Avoid a crash when converting null values in the native AST.
=> [Node.go] Export nil property values in the native AST as json null

assets/build/bindata.go, etc/build/etc/build/Dockerfile.build.alpine.tpl
`ADD` invalidates build cache ([more info](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#add-or-copy))
So currently it's impossible to build any of the drivers without having access to the internet
This will make it so I can easily build my drivers from a coffee place without WiFi
=> sdk: replace ADD with wget to avoid requiring internet to build

uast/ann/ann.go, uast/ann/ann_test.go, uast/iter.go
The test would otherwise panic without explaining why.
Signed-off-by: Francesc Campoy <campoy@golang.org>
=> improve message for inorder traversal of non binary nodes

uast/transformer/positioner/positions.go, uast/transformer/positioner/positions_test.go
=> On 1-indexed empty files the max column checked is 1

manifest/manifest.go, manifest/manifest_test.go
To be able to automatically generate supported drivers list (https://github.com/bblfsh/documentation/issues/135) add following information to manifest files:
* human-readable name
* list of supported features (AST, UAST, Roles)
=> add more metadata to manifests

manifest/discovery/discovery.go, manifest/discovery/discovery_test.go, manifest/manifest.go
Driver discovery uses public Github API to list all supported drivers and their manifests.
This functionality will be used by [language table generator](https://github.com/bblfsh/documentation/pull/141) for docs repository and [bblfshd](https://github.com/bblfsh/bblfshd/pull/148) to get the list of official/recommended drivers.  
=> Move driver discovery from docs repository to SDK

cli/bblfsh-sdk-tools/cmd/ast2gv.go, cli/bblfsh-sdk-tools/main.go
Typical usage:
`bblfsh-sdk-tools ast2gv --type=type --out=svg ./fixtures/*.native`
Output:
=> Add a tool to visualize native AST

assets/build/bindata.go, etc/build/make/bootstrap.mk
(this is for ~v2 since ~master is probably best left for critical fixes until we merge both branches to avoid complicating that final merge too much).
Don't consider git-untracked files to mark a docker build (or not) as dirty. This mainly avoids having caches and temporals generated by the build system or languages marking the images as dirty, which has given non-obvious problems more than once with CI of some drivers that naturally generate temporal files (like Python's `__pycache__`, `.mypy` and other files/directories).
=> Don't consider untracked files for marking a build as dirty

sdk/driver/driver.go, sdk/driver/fixtures/fixtures.go
=> Allow to dump a preprocessed UAST in fixture tests

cmd/bblfsh-sdk/cmd/update.go
Sometimes it's useful to change managed files to debug driver build in CI. This PR adds an environment variable that allows disabling managed files check completely.
=> Allow to bypass managed file checker

assets/build/bindata.go, etc/build/Dockerfile.tpl
Optimize build steps order to use Docker image cache more effectively.
=> Optimize build steps order

sdk/driver/fixtures/fixtures.go, uast/transformer/ops.go, uast/transformer/transformer.go
Address performance issues in the last SDK version.
In short: large transforms are an order of magnitude faster now. 
```
benchmark                         old ns/op      new ns/op     delta
BenchmarkGoDriver/transform-4     3181055629     261985232     -91.76%
benchmark                         old allocs     new allocs     delta
BenchmarkGoDriver/transform-4     18913347       561193         -97.03%
benchmark                         old bytes      new bytes     delta
BenchmarkGoDriver/transform-4     2509354920     54671790      -97.82%
```
=> Optimize UAST transforms

assets/build/bindata.go, etc/build/make/bootstrap.mk
Backport of fix for the v1 (master) branch, needed for the CI in python-driver/pull/162 to work.
=> Backport -uno parameter for git in makefiles

cmd/bblfsh-sdk-tools/cmd/ast2gv.go
AST2GV is a tool that converts a YML AST file to Graphviz/SVG/PNG image.
This PR adds two new CLI options:
* omit positional nodes,
* omit empty fields.
Currently, an AST might look a bit overloaded with information:
With both options enabled the result is much more readable:
=> ast2gv: allow to omit position info and nil fields

assets/skeleton/bindata.go, build/dev.go, build/test.go, cmd/bblfsh-sdk/cmd/build.go, etc/skeleton/.travis.yml
* Remove `_got` files left by failed integration test when the test passes.
* Test with a specific `bblfshd` version instead of pulling `latest` .
=> Small improvements for CLI

assets/skeleton/bindata.go, etc/skeleton/Gopkg.toml, etc/skeleton/driver/fixtures/fixtures_test.go.tpl
* Fix fixtures test template for new drivers
* Include `Gopkg.toml` into the driver skeleton
=> Fix template for new drivers

uast/transformer/positioner/positions.go
Drivers use (and the dashboard expect) a closed-open interval, so a len 4 identifier starting from 1 would have start,end columns (1,5).
This changes the check in the SDK that checks that the end column doesn't exceed the line length, because without the change an identifier that would end in a line without a newline (ie the last identifier of a file not finished with an endline) would trigger an error.
Fixes bblfsh/python-driver/issues/164.
=> Increase checked max line column by 1

uast/nodes/external.go, uast/nodes/node.go, uast/nodes/node_test.go
Since the new libuast version will be written in Go, there is a need to abstract UAST node type that is used in the code to allow to pass different implementations (implemented by client languages).
This CL defines a new `nodes.External` interface that will be implemented by native nodes, and checks for this kind of nodes in `ToNode`, so existing code will be able to handle external nodes at least by copying them.
It also updates `KindOf`, `Count` and `WalkPreOrder` functions to support external nodes instead of accepting only native ones.
=> Accept external node implementations

build/push.go
We are now ready to publish v2 drivers, thus we need to allow build scripts in SDK to push the `latest` tag to Docker hub.
To be on the safe side, I also print the variables that were used to make a decision to push. It seems like something weird happens with those vars during the merge to `master` and publishing a release.
=> Push drivers to the latest Docker tag

uast/query/iter.go, uast/query/iter_test.go, uast/query/query.go, uast/query/xpath/node.go, uast/query/xpath/query.go, uast/query/xpath/query_test.go, uast/query/xpath/xpath.go
Implement XPath filtering and iterators in the SDK. It will be exposed to the new libuast and the Go client.
Work in progress.
**TODO:**
=> Implement XPath filtering and iterators

uast/iter.go, uast/iter_test.go, uast/nodes/iter.go, uast/nodes/iter_test.go, uast/query/iter.go, uast/query/query.go, uast/types.go, uast/uast.go
* move base iterators to nodes package
* implement ToNode, TypeOf and NodeAs in terms of external nodes
* implement positional iterator
=> Move iterators to the nodes package and implement positional iterator

uast/nodes/hash.go, uast/nodes/node_test.go, uast/uast.go
Implement node hashing using SHA-256 and a simple serialization routine.
Note that it will hash the whole tree including positions. To omit positions, the caller will need to remove them from the tree.
=> Implement node hashing

driver/manifest/discovery/discovery.go, driver/manifest/discovery/discovery_test.go
Until we host a static manifest with the list of drivers, I propose to skip test failures if an error is due to rate limiting.
In any case, rate limiting affects 30-50% of our builds, thus the other 50-70% will be able to verify that the test passes (or not).
=> Ignore Github rate limit errors in tests

uast/nodes/node.go
Provide extra type safety for unique node keys that are used in maps. Previously it was possible to accidentally use the Node itself as a map key since `interface{}` type returned by `UniqueKey` allows this.
=> Provide extra type safety for unique node keys

driver/manifest/discovery/discovery.go
Use a static list served by https://github.com/bblfsh/documentation/pull/198 when hitting a Github rate limit during driver discovery.
=> Fallback to a static driver list when hitting rate limit

build/dev.go, build/test.go, cmd/bblfsh-sdk/cmd/fixtures.go, driver/driver.go, driver/errors/errors.go, driver/impl.go, driver/native/main.go, driver/native/native.go, driver/native/native_test.go, driver/server/grpc.go, driver/transforms.go, protocol/driver.go
Define common errors for native drivers and propagate them properly via gRPC boundary.
The list of errors so far:
- Syntax error (`ErrSyntax`): either partial or no UAST is returned. In gRPC, the status is `OK`, but an `Errors` field of the response contains error descriptions. 
- Native driver failure (`ErrDriverFailure`): native driver crashed or the native protocol connection is broken.  This indicates a bug in the driver and should be reported. Unrecoverable when returned by the driver. Driver server (either Go or `bblfshd`) should attempt a native driver restart before returning this error to the client.
- Transformation failed (`ErrTransformFailure`): parsing was succesful, but transformation pipeline for selected `Mode` fails to process it. This indicates a bug in the driver and …
=> Define and propagate driver error codes

assets/skeleton/bindata.go, etc/skeleton/.travis.yml
Override `install` step in Travis so that it doesn't execute `go get` automatically.
Also, update a bblfshd version.
=> Update CI files

build/test.go, driver/fixtures/fixtures.go
Add a special fixture `_syntax_error.*` that is checked to produce syntax error during integration tests (and any non-fatal error during fixture tests).
Related:
- https://github.com/bblfsh/python-driver/issues/169
- https://github.com/bblfsh/ruby-driver/issues/29
=> Add a test for syntax errors

assets/skeleton/bindata.go, cmd/bblfsh-sdk/cmd/update.go, etc/skeleton/driver/normalizer/transforms.go.tpl
The last missing piece of planned features for UASTv2. As mentioned in the design doc, native AST types should have namespaces matching the driver's language when the transformation is in Semantic mode. This will allow to avoid name collisions when analyzing ASTs for different languages.
=> Enable namespaces

cmd/util.go, cmd/util_test.go, common.go, driver/server/server.go
Part of the https://github.com/bblfsh/client-go/issues/102
Includes:
- move `sdk.BuildGRPCOptions` from bblfshd to SDK
- add same CLI `grpc-max-message-size` arg to all Drivers
=> Shared gRPC server config between bblfshd/driver

Gopkg.lock, driver/fixtures/fixtures.go, driver/impl.go, driver/native/native.go, driver/server/grpc.go, driver/server/server.go, driver/transforms.go, protocol/driver.go
Enable OpenTracing and instrument driver operations with spans.
=> Enable OpenTracing in SDK

uast/uast.go
`InlineImport` was discussed and approved in the beginning of Semantic UAST conversion, but was disabled in SDK until this time.
Thanks to the great work made by @juanjux on https://github.com/bblfsh/cpp-driver/pull/16, we now need to get this type back to SDK to use in C/C++ driver.
P.S. Sorry, there is no godoc for this type. Should be done separately by dumping parts of the design doc into Go files.
=> Reintroduce InlineImport

uast/transformer/arrays.go, uast/transformer/ops_test.go
`Append` operation in DSL accepts two parameters: an operation applied to the main part of an array (variable length) and the list of array operations applied to the tail of an array (fixed length).
For some reason, if the length of tail exactly matches the length of an input array, the transform passes `nil` to the main operation (variable length is zero). This might lead to a transformation failure, since the main operation might validate that passed object is an array and will fail with `nil`.
This was probably done at the early stages of DSL development to account for some specific cases. Right now the DSL contains all the functions needed, so this edge case should not appear in practice. 
This change makes `Append` to return an empty slice to the main operation for the case described …
=> Append should pass an empty array instead of nil

uast/transformer/errors.go, uast/transformer/transformer.go, uast/transformer/transformer_test.go
Currently, the transformation DSL performs the following validations:
* Variables in the destination should be defined in the source.
* All fields of an object should be used, or the transformation should be partial.
This, however, does not include the following validation:
* Variables defined in the source should be used in the destination.
This PR adds test cases for all mentioned validations and implements "unused variable" validation for the DSL.
P.S. Sorry, @juanjux, but you'll need to fix all of them in one way or another in the C++ driver.
=> DSL validation: unused variables

.travis.yml, build/test.go, cmd/bblfsh-sdk/cmd/build.go, driver/fixtures/fixtures.go
Add a `--bench` (`-b`) flag to `bblfsh-sdk test` to run benchmarks for the driver. All files with `./fixtures/bench_` will be used during the benchmark, and the results will be written to `bench.txt`.
Another possibility might be to add a flag to enable profiling in the driver, but this is not driver-related actually. The profile can only be enabled in the Go part of the driver, thus it will be measuring the performance of the transformation DSL. It can be analyzed without running the driver in Docker, by loading the same UAST file with SDK and importing the appropriate transformation package from the driver.
=> Enable fixtures benchmarks

uast/transformer/positioner/positions.go, uast/transformer/positioner/positions_test.go, uast/uast.go
As a part of an effort to fix positioning information in some drivers, this PR revisits the test cases for `positioner` object that fills in this information for drivers.
=> positioner: simplify, fix and add more tests

uast/types_test.go, uast/uast.go
We already have a `String` literal node, and this PR goes one step further and defines a boolean literal node (`Bool`) in SemUAST.
The definition of the node is pretty streightforward: it's a boolean value that can be either "true" or "false".
This node type is useless for some drivers without https://github.com/bblfsh/sdk/pull/337.
=> Define Bool node (boolean literal)

uast/types.go, uast/types_test.go
Some UAST schema types may contain fields with arrays of nodes. This change fixes the problem with loading such structs from generic UAST nodes to concrete Go types (currently it just fails).
=> uast: properly load node arrays with registered types

assets/skeleton/bindata.go, etc/skeleton/driver/normalizer/annotation.go, uast/transformer/positioner/positions.go, uast/transformer/positioner/positions_test.go
Currently, SDK only supports positional offset in bytes or line-column pair, where a column is given in bytes.
PR implements a new `Positioner` that converts Unicode character offsets to a byte offset and a line-column pair (in bytes as well).
Also, refactor long name for position functions to something shorter and place a deprecation note on the old ones.
This is change will allow to solve issues like https://github.com/bblfsh/javascript-driver/issues/25.
=> Support Unicode character offsets

assets/skeleton/bindata.go, driver/fixtures/fixtures.go, driver/transforms.go, etc/skeleton/driver/fixtures/fixtures_test.go.tpl, uast/transformer/positioner/tokens.go, uast/transformer/positioner/tokens_test.go
Changes in this PR enable the token extraction based on the source file and positional information. Needed for C# driver. And it can be used to improve other drivers as well.
- Implement a new `CodeTransformer` that uses positional offsets to update the token of AST nodes.
- Allow checking that positional information matches the token during fixtures tests.
- Add a new code-assisted transformation stage after `Preprocess` stage.
- Document the AST transformation pipeline.
This change also adds a deprecation note to the `Code` transformation stage. It was documented to run on the raw AST (`Native` stage), but it was always running at the end of the pipeline after all annotations were executed.
Drivers rely on real behavior, but there is no reason to run this stage so late in the pipeline. …
=> Support token extraction

uast/transformer/arrays.go, uast/transformer/ast.go, uast/transformer/ops.go, uast/transformer/ops_test.go
This is a combination of a few smaller changes required for C# driver.
First, it contains a change that breaks backward compatibility of one rarely used op for the sake of better naming. Previously `Any(sel)` operator was used to check if "any node in the array matches `sel`". PR renames this operator to `AnyElem` and defines a new function `Any()` that acts like "any node". This will allow us to replace a common pattern of `AnyNode(nil)` with `Any()`, which should be more readable.
The change won't break any drivers until they decide to update SDK version. I propose to just bump a minor version since the operation is very rare and the fix will only require to change the function name.
Next, PR defines a `HasFields` helper that can be used to check for presence or absence of specific …
=> More DSL operations to check objects

assets/skeleton/bindata.go, etc/skeleton/driver/normalizer/normalizer.go, etc/skeleton/driver/normalizer/transforms.go.tpl
During the last update of SDK I forgot to update managed skeleton files for drivers. Because of this, it's impossible to use the new `PreprocessCode` stage introduced in the new version (see CI failure in https://github.com/bblfsh/csharp-driver/pull/14).
PR updates skeleton files to allow the new stage.
This, however, will have some consequences for other drivers. Once an SDK is updated, it will include a new version of managed `transforms.go` file, that references a `PreprocessCode` global, which won't be available in old drivers. The fix is simple - include an empty stage with this name.
Another option may be to remove `transforms.go` from managed files. But it was added to this list on purpose. Each time SDK changes the transformation pipeline, the change should be considered by the …
=> Allow to use PreprocessCode stage

uast/transformer/semantic.go, uast/transformer/semantic_test.go, uast/uast.go
SDK defines a `uast.Comment` with multiple text components, namely `Prefix`, `Tab`, `Text` and `Suffix`. But to save some time we haven't implemented parsing of `Tab`.
This change implements `Tag` parsing properly. It also fixes problems with tab character detection in `Prefix` and `Suffix`.
This will change the way how `Comment` nodes are populated in Semantic mode. It only aligns the AST with the documented behavior though, so should be considered as a fix.
=> Split comments

uast/transformer/positioner/tokens.go
Fix the case where the token key is not set. The default `@token` should be assumed in this case.
=> Fix token verification when key is not set

uast/transformer/semantic.go
- Checks values returned by Index functions for -1 (had a case where it was -1, check failing CI in until this is merged in bblfsh/python-driver/pull/176).
- Trims the text before checking if the prefix and suffix exist with `HasPrefix` and `HasSuffix` to avoid cases where the language can give a wrong position for the start of the comment (or only the line) like happens with Python with some comments where it gives all the whitespace before if they're on their own line and indented.
=> More robust comment string parsing

uast/transformer/errors.go, uast/transformer/ops.go, uast/transformer/ops_test.go, uast/transformer/transformer_test.go
Fix a DSL validation bug discovered while working on C# driver. Also added more tests for similar cases.
As mentioned previously, the bug affected the DSL validation and may be a cause of dropped fields, since it gives no error for transforms that forget to specify a specific field that exists in the specific AST node type.
This may break existing drivers that exploited the bug, bypassing the validation by mistake.
=> Fix field usage validation when joining objects

README.md, cmd/bblfsh-sdk/cmd/build.go, driver/fixtures/docker.go, driver/fixtures/fixtures.go
This change consists of
- documentation for `bblfhs-sdk test`
- change default test timeout to 1 min
- always compile `fixtures.test` binary for linux OS, so it could always be run inside a container
=> Fix SDK test to run on non-linux os

uast/nodes/node.go, uast/nodes/node_test.go, uast/uast.go
Add a `ChildrenCount` helper (requested by https://github.com/bblfsh/client-go/issues/109) and relax argument constraints for `PositionsOf`, `RolesOf` and `TokenOf` (see https://github.com/bblfsh/client-go/issues/100).
Fixes https://github.com/bblfsh/client-go/issues/109.
=> Add few node helpers

uast/transformer/ops.go, uast/transformer/ops_test.go
As requested in https://github.com/bblfsh/cpp-driver/pull/26, add an option to drop a field. It will work the same way as `Optional: "x", Op: Any()`, except that it won't create a variable for `Optional`.
=> Add Drop operation to Fields

assets/build/bindata.go, etc/build/make/rules.mk
This change allows make build system inside the container to get a version number that will be embedded in go binary and override the default `dev-<shar>`
Fixes https://github.com/bblfsh/javascript-driver/issues/55
TODO:
=> build: propagate tag inside build container

uast/nodes/node.go, uast/nodes/node_test.go, uast/transformer/ast.go, uast/transformer/ops.go, uast/transformer/semantic.go, uast/transformer/transformer.go
This PR incorporates two optimizations found during recent profiling session.
First optimization changes `nodes.Equal` function to be more efficient. The function itself is pretty fast, but it executes so often that it dominates the execution time of the DSL (node filtering). The change inlines type-specific checks and defines a specialized `NodeEqual` function that omits interface convertions (`runtime.convI2I`).
The second optimization changes the `transform.FieldDescs` (field descriptors) from map to a struct with a slice. This increases the performance of range loops over this structure, resulting in ~30% DSL performance increase. The structure makes a difference, because `FieldDescs` is used during node matching for partial transformations that are used more often in recent driver. …
=> Optimize DSL

uast/transformer/semantic.go, uast/transformer/semantic_test.go
Comment parser does a correct check for the case when only stylistic characters are present, but it does not set the prefix correctly for this case.
=> Fix edge case for comment parsing

driver/fixtures/fixtures.go, uast/yaml/uastyml.go
Currently, all benchmarks including the ones for transformation pipeline run the driver instance to parse files. This prevents running those benchmarks on the host since driver runtime is necessary to parse files.
Instead, rewrite transformation pipeline benchmarks to use AST files generated by tests (fixture files). Those files will always be there since we use them to test the output of the driver.
This allows running this specific benchmark on the host, making results more stable.
A side effect is that, due to the way how `uast.RolesOf` is implemented, it will always append `Unannotated` role to all nodes that do not define roles and are not part of the Semantic UAST schema.
YAML encoder that is used to write fixtures in tests uses this function to dump native AST. As a result, all AST …
=> Allow to run driver UAST transform benchmark on the host

driver/native/internal/crash/main.go, driver/native/internal/crash/manifest.toml, driver/native/internal/crash/mock, driver/native/internal/simple/main.go, driver/native/native.go, driver/native/native_test.go
It turned out we don't have any logic to recover from a native driver crash (cool, right?).
`bblfshd` is of no help here since the Go driver server (the process that `bblfshd` starts in the container) usually survives the crash. `bblfshd` still thinks that the request failure was temporary and sends new requests, while driver server is not smart enough to restart the native driver process.
This change allows Go driver server to restart the native driver after a crash. As a bonus, it fixes an FD leak on driver close.
Logic is the following: if the driver server sees the end of `stdout` when waiting for a response, it assumes that the driver crashed, restarts it and returns an error to the client. The request of a next client (with a different file) may succeed this way.
Addresses #380 …
=> Restart native driver in case it crashes

driver/fixtures/fixtures.go
A small drive-by change fixing a typo in go doc.
=> doc: fix a typo

uast/types.go, uast/uast.go, uast/uast_test.go
Define a `uast.ContentOf` helper as requested in #376.
Fixes #376
=> Define a uast.ContentOf helper

driver/native/internal/simple/main.go, driver/native/native.go, driver/native/native_test.go
The fix included in #381 was not enough to fix #380. The case is a bit different: the driver first breaks the native protocol flow by printing on stdout, and then it crashes.
This PR makes sure to restart the driver in both cases and includes a new test case.
Fixes #380
=> Restart the driver in case the protocol is broken

uast/transformer/positioner/positions.go, uast/transformer/positioner/positions_test.go
Some native drivers (like JS) use a UTF-16 code point positions.
This change improves existing UTF-8 positioning tests and implements a UTF-16 positional index.
=> Implement UTF-16 code point index

build/sdk_update.go
Add a few missing operations to `bblfsh-sdk update` when switching to modules.
This change is may not be used in the future since I already used an updated `bblfsh-sdk` to update all the drivers. Still, I think it should be fixed for completeness.
=> More automation for SDK update to modules

build/build.go, build/build_test.go, driver/driver.go, driver/impl.go, driver/manifest/manifest.go, driver/manifest/manifest_test.go, driver/server/common.go, driver/server/grpc.go, driver/server/server.go, protocol/driver.go, protocol/driver.pb.go, protocol/driver.proto
This change defines a v2 endpoint for application version and the list of supported languages. It will finally allow moving https://github.com/bblfsh/bblfshd/pull/210 forward.
As a part of the change, define language aliases field in the driver manifest. This adds SDK support for https://github.com/bblfsh/bblfshd/issues/263.
The change is backward-compatible in the sense that it won't disable v1 language API in drivers, allowing to use them with older `bblfshd` versions.
But it also includes one breaking change for drivers. The internal driver interface has changed, thus drivers that declare a custom implementation would require few small changes. Note, however, that this is only true for drivers with custom implementations, and for now it only includes Go that is compiled directly into …
=> Language aliases and languages protocol v2

uast/transformer/positioner/positions.go, uast/transformer/positioner/positions_test.go
https://github.com/bblfsh/sdk/issues/382 requires exposing the positional index to be used in `libuast`/clients, so this change makes it public. Not sure why we had it private in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/401)
=> Expose positional index to use in libuast

uast/transformer/positioner/positions.go, uast/transformer/positioner/positions_test.go
Add reverse conversions from UTF-8/16 offsets to byte offsets. Required for https://github.com/bblfsh/libuast/issues/102.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/403)
=> Add reverse conversions from UTF-8/16 offsets

uast/transformer/positioner/positions.go, uast/transformer/positioner/positions_test.go
Support conversions from byte offset to Unicode/UTF-16 byte line-column pairs. Also, refactor the code for consistency and add more test cases.
This allows using positional info generated by Babelfish to calculate Unicode positions used in code editors.
Required by https://github.com/bblfsh/libuast/issues/102.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/405)
=> Support conversion to Unicode line-column positions

uast/nodes/iter.go, uast/nodes/iter_test.go, uast/query/iter.go
This issue came up multiple times recently. Some client functions want to list all children nodes exactly one level deep. This code is not a one-liner since it requires the user to check the type of the node and indirect, if necessary. It also requires to flatten arrays for object fields.
Thus, it seems we need to add some helper to expose this functionality to clients. The best way, in my opinion, is to make a new iteration order.
This PR adds a new `Children` iteration order that does all required checks and indirections.
Also, while here, add documentation for types and methods in the package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Implement node children iterator

uast/helpers.go, uast/helpers_test.go, uast/uast.go, uast/uast_test.go
As discussed in https://github.com/src-d/ml-backlog/issues/65 (non-public link), we should implement a helper for getting a list of import paths in the UAST.
PR implements a `uast.AllImportPaths` function that does all required checks and extracts a single deduplicated and sorted list of import paths.
The plan is to expose this functionality in `libuast` and then the clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/407)
=> Implement the "all import paths" helper

uast/types.go, uast/types_test.go, uast/uast_test.go
Fix a few issues discovered in the reflect-based UAST node loader. Discovered when hacking on C++ ASTs:
* Properly load nodes into custom interface fields.
* Loader must not create empty struct and maps when the node is `nil`.
* Add a bit more docs and tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/409)
=> Fix issues with reflect-based node loader

Makefile, assets/skeleton/bindata.go, etc/skeleton/driver/normalizer/normalizer.go
I found these while investigating https://github.com/bblfsh/go-driver/issues/48. We may also need to update the generated code itself, but for now this is only a comment fix with no functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/412)
=> docs: Fix godoc.org links in exported name comments.

assets/skeleton/bindata.go, build/sdk_update.go, driver/server/server.go, etc/skeleton/Jenkinsfile.tpl
As far as it was agreed that all supported drivers will be performance tested each time they receive commit in master, we came to conclusion that it would be more convenient to include Jenkinsfile template inside the drivers skeleton.
Type of benchmarks: transformations level and end-to-end level with bblfsh+driver installed setup
Test data: source code files inside the ./fixtures directory with a bench prefix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/414)
=> add Jenkinsfile template to the driver skeleton

assets/skeleton/bindata.go, etc/skeleton/Jenkinsfile.tpl
As was figured out after all the merges of drivers, previous transformations benchmark command was only applicable to the `go-driver` and fails on the others.
This fix changes benchmark command to be universal for drivers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/417)
=> fix Jenkinsfile template to support all languages drivers

uast/nodes/iter.go, uast/nodes/iter_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/422)
=> Fixes ChildrenOrder

uast/nodes/iter.go, uast/query/xpath/query_test.go, uast/query/xpath/xpath.go
Recovers from the panic, in case it is thrown when executing the xpath query and throws an error instead. When executing, in the `python-client` after this changes, the query:
```python
import bblfsh
client = bblfsh.BblfshClient("localhost:9432")
ctx = client.parse("./file.php")
ctx.filter("//*[@role='Variable']*//Name")
```
the python interpreter no longer explodes and we are shown a friendlier message:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.7/site-packages/bblfsh/result_context.py", line 34, in filter
return NodeIterator(self.ctx.filter(query), self.ctx)
RuntimeError: Error executing the xPath query, maybe wrong syntax?
```
Since the modified method was already returning an error (but was not handling the panic and therefore Go …
=> Handles errors in the xpath queries gracefully

uast/role/role.go
Currently, as noted in https://github.com/bblfsh/php-driver/pull/56#issuecomment-522348679, drivers use the `Default` role differently in switch statements: some include the `Case` role, while others omit it when the case is a `Default` one.
This PR clarifies the usage of `Default` and requires the `Case` role to be set as well for switch statements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/427)
=> Clarify usage of Default role in switch statements

cmd/bblfsh-drivers-updater/update.go
removed problematic `fallthrough` from switch that validates script and sdk version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/428)
=> fix drivers updater validation

cmd/bblfsh-sdk/cmd/request.go
`encoding` field of the payload generated by `bblfsh-sdk request` should be `Encoding` instead to not make drivers crash if we test them with that tool.
That would make the field match https://github.com/bblfsh/sdk/blob/77c81e6f6883d2aa9f57acfabd4a6099e8eac2ef/driver/native/native.go#L137
Signed-off-by: ncordon <nacho.cordon.castillo@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/sdk/441)
=> Turns encoding field into Encoding in bblfsh-sdk request
